<x-layouts::app :title="'Editar '.$page->name">
    <form method="POST" action="{{ route('admin.pages.update', $page) }}" class="mx-auto w-full max-w-5xl space-y-8">
        @csrf @method('PUT')
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-blue-700">Contenido</p><h1 class="mt-1 text-3xl font-bold">{{ $page->name }}</h1><p class="mt-2 text-sm text-slate-600">Edite textos y datos sin alterar la estructura visual aprobada.</p></div><div class="flex gap-3"><a href="{{ route($page->slug) }}" target="_blank" class="secondary-button">Vista previa ↗</a><button class="primary-button" type="submit">Guardar cambios</button></div></div>
        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p class="font-semibold">Revise los campos indicados.</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <section class="legal-card p-6"><h2 class="text-xl font-semibold">Página y SEO</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-medium" for="name">Nombre interno</label><input id="name" name="name" value="{{ old('name', $page->name) }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></div><div><label class="text-sm font-medium" for="title">Título principal</label><input id="title" name="title" value="{{ old('title', $page->title) }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></div><div><label class="text-sm font-medium" for="meta_title">Meta title</label><input id="meta_title" name="meta_title" value="{{ old('meta_title', $page->meta_title) }}" maxlength="70" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></div><div><label class="text-sm font-medium" for="og_image">Imagen Open Graph</label><input id="og_image" name="og_image" value="{{ old('og_image', $page->og_image) }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5" placeholder="site/imagen.webp o URL completa"></div><div class="sm:col-span-2"><label class="text-sm font-medium" for="meta_description">Meta description</label><textarea id="meta_description" name="meta_description" maxlength="170" rows="3" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5">{{ old('meta_description', $page->meta_description) }}</textarea></div><label class="flex items-center gap-3 text-sm font-medium"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $page->is_active)) class="rounded border-slate-300 text-blue-700">Página publicada</label></div></section>
        <div class="space-y-5">
            @foreach($page->sections as $section)
                <section class="legal-card p-6" wire:key="section-{{ $section->id }}"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="data-label text-blue-700">{{ $section->section_key }}</p><h2 class="mt-1 text-lg font-semibold">{{ $section->title ?: 'Sección sin título' }}</h2></div><label class="flex items-center gap-2 text-sm"><input type="hidden" name="sections[{{ $section->id }}][is_active]" value="0"><input type="checkbox" name="sections[{{ $section->id }}][is_active]" value="1" @checked(old("sections.{$section->id}.is_active", $section->is_active)) class="rounded border-slate-300 text-blue-700">Visible</label></div><div class="mt-5 grid gap-5"><div><label class="text-sm font-medium" for="section-title-{{ $section->id }}">Título</label><input id="section-title-{{ $section->id }}" name="sections[{{ $section->id }}][title]" value="{{ old("sections.{$section->id}.title", $section->title) }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></div><div><label class="text-sm font-medium" for="section-subtitle-{{ $section->id }}">Subtítulo / descripción</label><textarea id="section-subtitle-{{ $section->id }}" name="sections[{{ $section->id }}][subtitle]" rows="3" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5">{{ old("sections.{$section->id}.subtitle", $section->subtitle) }}</textarea></div><div><div class="flex items-center justify-between"><label class="text-sm font-medium" for="section-content-{{ $section->id }}">Contenido estructurado</label><span class="text-xs text-slate-500">Conserve las claves; puede editar sus valores y listas.</span></div><textarea id="section-content-{{ $section->id }}" name="sections[{{ $section->id }}][content]" rows="10" spellcheck="false" class="mt-2 w-full rounded-lg border border-slate-300 bg-slate-950 px-4 py-3 font-mono text-xs leading-5 text-slate-100">{{ old("sections.{$section->id}.content", json_encode($section->content, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) }}</textarea></div><div class="max-w-32"><label class="text-sm font-medium" for="section-order-{{ $section->id }}">Orden</label><input id="section-order-{{ $section->id }}" type="number" min="0" max="999" name="sections[{{ $section->id }}][sort_order]" value="{{ old("sections.{$section->id}.sort_order", $section->sort_order) }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></div></div></section>
            @endforeach
        </div>
        <div class="flex justify-end"><button class="primary-button" type="submit">Guardar todos los cambios</button></div>
    </form>
</x-layouts::app>
