<x-layouts::app :title="'Solicitud de '.$submission->name">
    <div class="mx-auto w-full max-w-4xl space-y-7">
        <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><a href="{{ route('admin.contacts.index') }}" class="text-sm font-semibold text-blue-700">← Volver a solicitudes</a><h1 class="mt-2 text-3xl font-bold">{{ $submission->name }}</h1><p class="mt-2 text-sm text-slate-600">Recibida el {{ $submission->created_at->format('d/m/Y \a \l\a\s H:i') }}</p></div><form method="POST" action="{{ route('admin.contacts.update', $submission) }}" class="flex items-end gap-3">@csrf @method('PATCH')<div><label class="text-xs font-semibold" for="status">Estado</label><select id="status" name="status" class="mt-1 rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@foreach($statuses as $status)<option value="{{ $status->value }}" @selected($submission->status === $status)>{{ ucfirst(strtolower($status->value)) }}</option>@endforeach</select></div><button class="primary-button" type="submit">Actualizar</button></form></div>
        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
        <section class="legal-card p-6"><h2 class="text-xl font-semibold">Datos de contacto</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="data-label">Empresa / Organización</dt><dd class="mt-1 text-sm font-medium">{{ $submission->company }}</dd></div><div><dt class="data-label">Cargo</dt><dd class="mt-1 text-sm font-medium">{{ $submission->position ?: 'No informado' }}</dd></div><div><dt class="data-label">Correo</dt><dd class="mt-1 text-sm"><a href="mailto:{{ $submission->email }}" class="font-semibold text-blue-700">{{ $submission->email }}</a></dd></div><div><dt class="data-label">Teléfono</dt><dd class="mt-1 text-sm font-medium">{{ $submission->phone ?: 'No informado' }}</dd></div><div><dt class="data-label">Usuarios estimados</dt><dd class="mt-1 text-sm font-medium">{{ $submission->estimated_users ?: 'No informado' }}</dd></div><div><dt class="data-label">Dirección IP</dt><dd class="mt-1 font-mono text-xs text-slate-500">{{ $submission->ip_address ?: 'No disponible' }}</dd></div></dl></section>
        <section class="legal-card p-6"><h2 class="text-xl font-semibold">Necesidades</h2><div class="mt-4 flex flex-wrap gap-2">@forelse($submission->needs ?? [] as $need)<span class="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-medium text-blue-700">{{ str($need)->replace('-', ' ')->title() }}</span>@empty<span class="text-sm text-slate-500">No especificadas.</span>@endforelse</div></section>
        <section class="legal-card p-6"><h2 class="text-xl font-semibold">Mensaje</h2><p class="mt-4 whitespace-pre-line text-sm leading-7 text-slate-700">{{ $submission->message }}</p></section>
    </div>
</x-layouts::app>
